export const FETCH_INSTRUCTORS_SUCCESS = "FETCH_INSTRUCTORS_SUCCESS";
export const FETCH_INSTRUCTORS_FAIL = "FETCH_INSTRUCTORS_FAIL";
export const CREATE_INSTRUCTOR = "CREATE_INSTRUCTOR";

export const CREATE_USER = "CREATE_USER";
export const FETCH_USERS = "FETCH_USERS";

export const CREATE_REVIEW = "CREATE_REVIEW";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAIL = "FETCH_REVIEWS_FAIL";

export const CREATE_COURSE = "CREATE_COURSE";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAIL = "FETCH_COURSES_FAIL";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const CREATE_BLOG = "CREATE_BLOG";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_BLOGS_FAIL = "FETCH_BLOGS_FAIL";

export const POST_PHOTO = "POST_PHOTO";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAIL = "FETCH_PHOTOS_FAIL";

export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
