export const FETCH_INSTRUCTORS = "FETCH_INSTRUCTORS";
export const CREATE_INSTRUCTOR = "CREATE_INSTRUCTOR";

export const CREATE_USER = "CREATE_USER";
export const FETCH_USERS = "FETCH_USERS";

export const CREATE_REVIEW = "CREATE_REVIEW";
export const FETCH_REVIEWS = "FETCH_REVIEWS";

export const CREATE_COURSE = "CREATE_COURSE";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAIL = "FETCH_COURSES_FAIL";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const CREATE_BLOG = "CREATE_BLOG";
export const FETCH_BLOGS = "FETCH_BLOGS";

export const POST_PHOTO = "POST_PHOTO";
export const FETCH_PHOTOS = "FETCH_PHOTOS";

export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
